(function(){
"use strict";
const db=window.FERRATA_DB;if(!db?.routes)return;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const proxyImage=url=>"https://images.weserv.nl/?url="+encodeURIComponent(url)+"&w=900&h=600&fit=cover&output=webp";
const operators={
 loser:{name:"Loser Panoramabahn",price:"≈ €29 туда–обратно",hours:"осенью обычно 08:30–16:00; в октябре возможна работа только по выходным",url:"https://www.loser.at/",note:"Если канатка закрыта, оператор обычно публикует статус платной дороги."},
 katrin:{name:"Katrinbahn",price:"€28 туда–обратно",hours:"04.04–09.11.2026 · ежедневно 09:00–17:00",url:"https://en.katrinseilbahn.com/betriebszeiten",note:"Тариф и сезон 2026 подтверждены оператором."},
 kampenwand:{name:"Kampenwandseilbahn",price:"€28 туда–обратно",hours:"с 15.09 · ежедневно 09:00–17:00",url:"https://www.kampenwand.de/preise-tickets/ticketpreise-sommer",note:"Для раннего подъёма 09:00–09:30 тариф немного ниже."},
 jenner:{name:"Jennerbahn",price:"€47 туда–обратно",hours:"летний сезон до 08.11.2026 · альпинистский рейс 08:30, последний спуск 17:00",url:"https://www.jennerbahn.de/en/jennerbahn-ticket-prices-summer-2026-koenigssee-cable-car/",note:"Перед выездом проверить дневной статус и погоду."},
 nordkette:{name:"Nordkette",price:"≈ €48–56 туда–обратно",hours:"25.04–01.11.2026 · Seegrubenbahn 08:30–17:30, Hafelekarbahn 09:00–16:45",url:"https://nordkette.com/en/facilities-/-timetable/",note:"Цена зависит от конечной станции; для ферраты сверить нужный билет."},
 gosaukamm:{name:"Gosaukammbahn",price:"€27.90 туда–обратно",hours:"14.09–01.11.2026 · ежедневно 08:15–17:00, каждые 15 минут",url:"https://www.dachstein.at/en/summer/cable-cars/gosaukammbahn",note:"Последний подъём и спуск — к окончанию указанного интервала."},
 karwendel:{name:"Karwendelbahn Mittenwald",price:"≈ €42–48 туда–обратно",hours:"14.09–11.10.2026 · 08:30–17:30; последний подъём на 30 минут раньше",url:"https://www.karwendelbahn.de/",note:"Маршрут длинный: рассчитывать на первую кабину, а не на последний спуск."},
 feuerkogel:{name:"Feuerkogelbahn",price:"€31.50 туда–обратно",hours:"14.09–01.11.2026 · ежедневно 08:30–17:00",url:"https://www.feuerkogel.info/en/summer/open-cable-car",note:"С 09:00 обычно каждые 20 минут; при необходимости чаще."},
 rofan:{name:"Rofanseilbahn",price:"≈ €27–32 туда–обратно",hours:"летний/осенний режим; часы и погодный статус проверить в день поездки",url:"https://www.rofanseilbahn.at/",note:"Цена дана как бюджетный ориентир до проверки тарифа 2026."},
 tegelberg:{name:"Tegelbergbahn",price:"≈ €30–35 туда–обратно",hours:"летний режим; последний спуск и ревизию проверить у оператора",url:"https://www.tegelbergbahn.de/",note:"Канатка удобна для организации спуска; схема зависит от направления маршрута."},
 mooserboden:{name:"Трансфер Kesselfall → Mooserboden",price:"≈ €28–35 туда–обратно",hours:"сезонный автобус + наклонный подъёмник; доступ зависит от погоды и дневного статуса",url:"https://www.verbund.com/en-at/about-verbund/visitors-centres/kaprun-high-mountain-reservoirs",note:"На своей машине к плотинам не проехать; это обязательный транспорт комплекса."},
 krippenstein:{name:"Dachstein Krippenstein",price:"€46.70 Panorama Ticket",hours:"01.05–01.11.2026 · первый подъём 08:40; кабины примерно каждые 15 минут",url:"https://www.dachstein-salzkammergut.com/en/news/operation-times",note:"Билет включает секции 1–3; проверить, какая секция нужна для выбранной линии."},
 alpspitz:{name:"Alpspitzbahn",price:"≈ €38–44 туда–обратно",hours:"октябрь 2026 · 08:30–17:00; последний подъём на 30 минут раньше",url:"https://zugspitze.de/en/Service-information/Opening-hours-timetables",note:"Точный тариф зависит от выбранного билета Garmisch-Classic."},
 fieberbrunn:{name:"Streubödenbahn F1+F2",price:"≈ €30–38 туда–обратно",hours:"14.05–01.11.2026 · ежедневно 08:30–17:00",url:"https://www.fieberbrunn.com/sommerbahnen",note:"Полный маршрут к Wildseeloder длиннее самой ферраты: держать запас к 17:00."},
 steinplatte:{name:"Steinplatte",price:"канатка на 10.10 не рассчитана",hours:"летняя канатка завершает сезон раньше; проверять платную дорогу и парковку",url:"https://www.steinplatte.tirol/de/pistenstatus-highlights.html",note:"Для этой даты основной вариант доступа — дорога, только если она официально открыта."}
};
const routeLift={13:"loser",15:"katrin",16:"kampenwand",17:"jenner",18:"jenner",27:"nordkette",28:"gosaukamm",29:"karwendel",32:"feuerkogel",34:"rofan",35:"tegelberg",37:"mooserboden",43:"krippenstein",45:"alpspitz",49:"mooserboden",53:"feuerkogel",54:"katrin",55:"loser",56:"fieberbrunn",57:"fieberbrunn",58:"fieberbrunn",61:"steinplatte"};
const componentLift={"sophie klettersteig":"loser","sisi klettersteig":"loser","katrin 7-seenblick":"katrin","kampenwand":"kampenwand","kampenwand klettersteig":"kampenwand","laxersteig":"jenner","schützensteig":"jenner","innsbrucker klettersteig":"nordkette","donnerkogel":"gosaukamm","mittenwalder klettersteig":"karwendel","alberfeldkogel":"feuerkogel","haidachstellwand":"rofan","tegelbergsteig":"tegelberg","höhenburg klettersteig":"mooserboden","mobo 107":"mooserboden","krippenstein nordwand":"krippenstein","alpspitz-ferrata":"alpspitz","marokka klettersteig":"fieberbrunn","himmel & henne":"fieberbrunn","wildseelodersee":"fieberbrunn","s’schuastagangl":"steinplatte"};
function infoFor(r,c){const key=c?componentLift[String(c.name||"").toLowerCase()]:routeLift[r.id];return key?{needed:key!=="steinplatte",...operators[key],key}:{needed:false,name:"Канатка не нужна",price:"€0",hours:"Старт пешком от парковки / населённого пункта",url:r.topo||"",note:"Проверь платную дорогу, парковку и ограничения доступа отдельно."}}
function rainLevel(mm){mm=Number(mm);if(!Number.isFinite(mm))return{key:"unknown",label:"Нет данных",text:"Нельзя оценить по миллиметрам."};if(mm===0)return{key:"dry",label:"0 мм · модельно сухо",text:"Скала может остаться мокрой после вчерашнего дождя, росы или тумана."};if(mm<=1)return{key:"caution",label:"0.1–1 мм · осторожно",text:"Даже короткий дождь способен намочить ключевые плиты и спуск."};if(mm<=3)return{key:"risk",label:"1.1–3 мм · высокий риск",text:"Для ферраты это уже потенциально критично, особенно на гладкой или теневой скале."};return{key:"critical",label:">3 мм · критично",text:"Планировать сухую альтернативу; не считать маршрут пригодным без локальной проверки."}}
window.FERRATA_LOGISTICS={infoFor,rainLevel,operators};
function mountHome(){document.querySelectorAll("#cards>.card").forEach(el=>{const r=db.routes[Number(el.dataset.orig)];if(!r)return;const top=el.querySelector(".topline");if(top){const badge=top.querySelector(".badge");if(badge)top.prepend(badge);const rank=top.querySelector(".rank");if(rank)top.append(rank)}const meta=el.querySelector(".cardDataChips");if(meta&&!el.querySelector(".liftChip")){const li=infoFor(r);meta.insertAdjacentHTML("beforeend",'<span class="liftChip '+(li.needed?'liftNeeded':'liftNone')+'">🚡 '+esc(li.needed?li.price:"не нужна")+'</span>')}})}
function mountDetail(){const slug=new URL(location.href).searchParams.get("route"),r=db.routes.find(x=>x.slug===slug||String(x.id)===slug);if(!r)return;const status=$("statusBox"),overview=$("overview");if(status&&overview)overview.querySelector("h2")?.after(status);const section=$("route");if(section&&!$("transportPlan")){const li=infoFor(r);const hasParts=Boolean(r.components?.length);const parts=(hasParts?r.components:[{name:r.name,kind:"ferrata"}]).map(c=>{const ci=hasParts?infoFor(r,c):li;return '<div class="transportRow"><div><b>'+esc(c.name)+'</b><small>'+esc(ci.name)+'</small></div><span class="transportPrice">'+esc(ci.price)+'</span><p>'+esc(ci.hours)+'. '+esc(ci.note)+'</p>'+(ci.url?'<a href="'+esc(ci.url)+'" target="_blank" rel="noopener noreferrer">Официальный оператор / доступ ↗</a>':'')+'</div>'}).join("");section.insertAdjacentHTML("afterbegin",'<div id="transportPlan" class="transportPlan"><div class="atlasEyebrow">Канатка и доступ</div><h2>'+(li.needed?'🚡 Учти подъёмник':'🥾 Подъёмник не требуется')+'</h2><p class="transportIntro">Цена указана за взрослого ориентировочно. Расписание и последний спуск проверяй утром поездки: ветер и техработы меняют режим.</p><div class="transportRows">'+parts+'</div></div>')}
const src=$("sourcesLinks"),sources=$("sources");if(src&&sources&&!$("sourceGallery")){const pics=[...(r.photos||[])];if(r.topoImage)pics.push(r.topoImage);if(pics.length){src.insertAdjacentHTML("beforebegin",'<div id="sourceGallery" class="sourceGallery" aria-label="Изображения из первоисточников">'+pics.slice(0,6).map(p=>'<a href="'+esc(p.source||p.src)+'" target="_blank" rel="noopener noreferrer"><img src="'+esc(p.src)+'" data-proxy-fallback="'+esc(proxyImage(p.src))+'" alt="'+esc(p.alt||r.name)+'" loading="lazy"><span>'+esc(p===r.topoImage?'Топо':'Фото')+' ↗</span></a>').join("")+'</div>');$("sourceGallery").addEventListener("error",event=>{const img=event.target;if(!(img instanceof HTMLImageElement))return;if(img.dataset.proxyFallback){const next=img.dataset.proxyFallback;delete img.dataset.proxyFallback;img.src=next;return}img.closest("a")?.remove();if(!$("sourceGallery")?.querySelector("img"))$("sourceGallery")?.remove()},true)}}}
if(document.body.dataset.page==="index")mountHome();else if(document.body.classList.contains("atlasDetail"))mountDetail();
})();
